FROM ubuntu:latest

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -y && apt-get upgrade -y && \
  apt-get install -y gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf \
  qemu-user-static wget build-essential cmake just

