import os
import re
import sys

# Regex to find lines like: #define MYCONF 1
CONFIG_REGEX = re.compile(r"^#define\s+((\w+))\s+([01])")
INCLUDE_DIR = os.path.join(os.path.abspath(__file__), "include")
CONFIG_FILENAME = "config.h"
CONFIG_PATH = os.path.join(INCLUDE_DIR, CONFIG_FILENAME)
GENERATED_FILENAME = "config_macros.h"
GENERATED_PATH = os.path.join(INCLUDE_DIR, GENERATED_FILENAME)

def generate_header():
    """Parses the input header and generates an output header with helper macros."""


    generated_lines = [
        "#pragma once\n\n",
        "// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.\n",
        "// YOU SHOULD REGENERATE THIS FILE ONLY WHEN ADDING OR REMOVING\n",
        "// CONFIGURATION OPTIONS, THERE IS NO NEED TO REGENERATE WHEN CHANGING THEM.\n"
        f"#include <{CONFIG_FILENAME}>\n\n",
    ]

    try:
        with open(CONFIG_PATH, 'r') as f:
            for line in f:
                match = CONFIG_REGEX.match(line)
                if not match:
                    continue

                conf_name = match.group(1)    # e.g., MYCONF

                generated_lines.append(f"#if {conf_name}\n")
                generated_lines.append(f"#define {conf_name}_ENABLED 1\n")
                generated_lines.append(f"#define IF_{conf_name}(...) __VA_ARGS__\n")
                generated_lines.append(f"#define IF_NOT_{conf_name}(...) /* {conf_name} Enabled */\n")
                generated_lines.append("#else\n")
                generated_lines.append(f"#define {conf_name}_DISABLED 1\n")
                generated_lines.append(f"#define IF_{conf_name}(...) /* {conf_name} Disabled */\n")
                generated_lines.append(f"#define IF_NOT_{conf_name}(...) __VA_ARGS__\n")
                generated_lines.append("#endif\n\n")

    except FileNotFoundError:
        print(f"Error: Input file '{CONFIG_PATH}' not found.")
        sys.exit(1)

    with open(GENERATED_PATH, 'w') as f:
        f.writelines(generated_lines)

    print(f"Successfully generated '{GENERATED_PATH}' from '{CONFIG_FILENAME}'.")

if __name__ == "__main__":
    generate_header()
