#pragma once

// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.
// YOU SHOULD REGENERATE THIS FILE ONLY WHEN ADDING OR REMOVING
// CONFIGURATION OPTIONS, THERE IS NO NEED TO REGENERATE WHEN CHANGING THEM.
#include "config.h"

#if DP_LOG
#define DP_LOG_ENABLED 1
#define IF_DP_LOG(...) __VA_ARGS__
#define IF_NOT_DP_LOG(...) /* DP_LOG Enabled */
#else
#define DP_LOG_DISABLED 1
#define IF_DP_LOG(...) /* DP_LOG Disabled */
#define IF_NOT_DP_LOG(...) __VA_ARGS__
#endif

#if DP_STATS
#define DP_STATS_ENABLED 1
#define IF_DP_STATS(...) __VA_ARGS__
#define IF_NOT_DP_STATS(...) /* DP_STATS Enabled */
#else
#define DP_STATS_DISABLED 1
#define IF_DP_STATS(...) /* DP_STATS Disabled */
#define IF_NOT_DP_STATS(...) __VA_ARGS__
#endif

#if DP_FREE_VALIDATION
#define DP_FREE_VALIDATION_ENABLED 1
#define IF_DP_FREE_VALIDATION(...) __VA_ARGS__
#define IF_NOT_DP_FREE_VALIDATION(...) /* DP_FREE_VALIDATION Enabled */
#else
#define DP_FREE_VALIDATION_DISABLED 1
#define IF_DP_FREE_VALIDATION(...) /* DP_FREE_VALIDATION Disabled */
#define IF_NOT_DP_FREE_VALIDATION(...) __VA_ARGS__
#endif

